// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Selenium {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void Selenium() {
    driver.get("https://lsy.u6.ru/timessquare/");
    driver.manage().window().setSize(new Dimension(1050, 708));
        driver.findElement(By.id("textfield-1024-inputEl")).sendKeys("COMPACT");
        driver.findElement(By.id("textfield-1025-inputEl")).sendKeys("QWErty123");
    driver.findElement(By.id("datefield-1037-inputEl")).click();
    driver.findElement(By.id("datefield-1037-inputEl")).sendKeys("21May21");
    driver.findElement(By.cssSelector(".x-grid-item-focused > .x-grid-cell-inner")).click();
    driver.findElement(By.id("button-1026-btnIconEl")).click();
  }
}
